# Generated by Django 5.2.1 on 2025-05-20 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_passanger'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Passanger',
            new_name='Passenger',
        ),
    ]
